### ISSUE TITLE
Support tilde (~) shortcut 

### ISSUE THREAD

**Issue by DavidBadura** [webmozart/path-util#10]
What do you think about it?

```php
echo Path::canonicalize('~/config.ini');
// => /home/myself/config.ini
```

**Comment by webmozart** [comment]
Thank you for the proposal! :) I don't really want to add this feature. `Path::canonicalize()` is used very often and should be as efficient as possible. Adding a 1% use case does not warrant the slower runtime of that method IMO.

**Comment by DavidBadura** [comment]
i have run some benchmarks with following if statement and i can't see any difference in the performance.

```php
if ($path[0] === '~') {
  // get home directory
}
```

to check if the string begins with `~` is super fast. so i don't think it is a performance difference.

**Comment by webmozart** [comment]
Thanks! What would be the home directory on Windows?

**Comment by DavidBadura** [comment]
that's a little bit tricky :wink: if i am at home i will create a PR.

**Comment by DavidBadura** [comment]
the only thing is, i don't know how to write tests for windows...

**Comment by King2500** [comment]
Depends on your implementation...

I think you can mock built-in functions (like `getenv`) so:
http://www.schmengler-se.de/en/2011/03/php-mocking-built-in-functions-like-time-in-unit-tests/

To the general topic:
I'm not a fan of this feature, since I think `~` is to plattform specific and is not supported by PHP built-in functions, right?
In the end, it is @webmozart 's decision ;-)

**Comment by DavidBadura** [comment]
Yes, it's not supported by PHP itself. But if you use `Path::canonicalize('~/config.ini')` so this path would be normalized to `/home/myself/config.ini` and it works with PHP built-in functions.

I write a lot of cli libs and use this lib to normalize path <3 but i have to catch `~` to support home directories.

I would add a new method `Path::getHomeDirectory()` and add this lines in `Path::canonicalize()`.

```php
if ($path[0] === '~') {
    $path = Path::getHomeDirectory() . substr($path, 1);
}
```

this shouldn't be a performance difference if you don't pass `~`

For linux is the method `getHomeDirectory()` very simple:

```php
return getenv('HOME');
```

For windows it's tricky:

```php
if (getenv('HOMEDRIVE') && getenv('HOMEPATH')) {
    // this works for >= windows8
    return getenv('HOMEDRIVE') . getenv('HOMEPATH');
}

// I found more on the internet. for <= windows7
$username = get_current_user() ?: getenv('USERNAME');
if ($username && is_dir($win7path = 'C:\Users\\' . $username)) {
    return $win7path;
}

if ($username) {
    // Vista
    return 'C:\Documents and Settings\\' . $username;
}

if (is_dir('C:\Users')) {
    return 'C:\Users';
}

return 'C:\Documents and Settings';
```

The questions are:

* support `~`?
* only for *nix?
* and for windows and which versions?

it would be nice to have a lib to kill all problems with path :wink:

**Comment by webmozart** [comment]
PHP apparently does not support `~`:

```
php -r "echo realpath('~');"
```

The various possibilities on Windows are the exact reason why I'm not sure whether we should really support this feature. However, we could support it on Unix only and throw an exception otherwise.

Thoughts?

**Comment by DavidBadura** [comment]
I think, we should support unix and >= windows8 because it's clearly.

```php
public function getHomeDirectory()
{
    if (getenv('HOME')) {
        return getenv('HOME');
    }

    if (getenv('HOMEDRIVE') && getenv('HOMEPATH')) {
        return getenv('HOMEDRIVE') . getenv('HOMEPATH');
    }

    throw new \RuntimeException('...');
}
```

**Comment by webmozart** [comment]
OK then :)

**Comment by DavidBadura** [comment]
done with #11
