### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by ishan-deepsource** [webmozart/path-util#36]
I see last commits 6 years ago and last release was on Dec 2015. Also, lots of PRs are unreviewed as well. So I was wondering if anybody is still maintaining the project?

**Comment by chalasr** [comment]
By now you should probably use the `Path` class from [symfony/filesystem](https://github.com/symfony/filesystem) instead.

**Comment by ishan-deepsource** [comment]
Hey @chalasr, I don't see `Path` class in [symfony/filesystem](https://github.com/symfony/filesystem). There's only `Filesystem` class I see at the moment.

Am I missing anything here?

**Comment by webmozart** [comment]
@ishan-deepsource The clas has been added [with Symfony 5.4](https://github.com/symfony/filesystem/tree/5.4).

**Comment by ishan-deepsource** [comment]
Ahh.. got it. Thanks.
